### ISSUE TITLE
Platform Support?

### ISSUE THREAD

**Issue by amilajack** [131/node-vlc-player#1]
This doesnt seem like it support multiple platforms. Is this correct?

**Comment by 131** [comment]
The indent of this module is mostly to provide binaries for windows, linux equivalent (that we explicitly require at the application level)  is a "dummy" : ```
"use strict";

var cp       = require('child_process');
var vlc_path = require('nyks/path/which')('vlc');
module.exports = function(/* args, options */) {
  return cp.spawn.bind(null, vlc_path).apply(null, arguments);
}
```

Also, you might want to take a look at https://github.com/ivsgroup/node-vlc-remote

PS : edited on the repo README, thx
